# Generated by Django 3.2.9 on 2021-12-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='update_days',
        ),
        migrations.AlterField(
            model_name='horse',
            name='active',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='horse',
            name='class1',
            field=models.CharField(blank=True, choices=[('AA', 'AA'), ('AC', 'AC'), ('CC', 'CC')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='class2',
            field=models.CharField(blank=True, choices=[('GG', 'GG'), ('GA', 'GA'), ('AA', 'AA')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='class3',
            field=models.CharField(blank=True, choices=[('AA', 'AA'), ('AC', 'AC'), ('CC', 'CC')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='distance1',
            field=models.CharField(blank=True, choices=[('CC', 'CC'), ('CT', 'CT'), ('TT', 'TT')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='distance2',
            field=models.CharField(blank=True, choices=[('CC', 'CC'), ('CT', 'CT'), ('TT', 'TT')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='elite',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='horse',
            name='optimal_distance',
            field=models.CharField(blank=True, choices=[('5-7f', '5-7f'), ('6-8f', '6-8f'), ('8-10f', '8-10f'), ('10f+', '10f+')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='size1',
            field=models.CharField(blank=True, choices=[('CC', 'CC'), ('CT', 'CT'), ('TT', 'TT')], max_length=5, null=True),
        ),
    ]
