# Generated by Django 3.2.9 on 2021-12-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0002_auto_20211202_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='active',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='horse',
            name='country',
            field=models.CharField(blank=True, choices=[('North America', 'North America'), ('Europe', 'Europe'), ('Overseas', 'Overseas'), ('Australia', 'Australia')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='elite',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='horse',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='horse',
            name='status',
            field=models.CharField(choices=[('Live', 'Live'), ('Retired', 'Retired'), ('Unraced', 'Unraced'), ('Unnamed', 'Unnamed')], default='unnamed', max_length=10),
        ),
        migrations.AlterField(
            model_name='horse',
            name='type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('National Hunt', 'National Hunt')], max_length=15),
        ),
    ]
