# Generated by Django 3.2.9 on 2021-12-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0003_auto_20211203_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gcs_bucket', models.CharField(max_length=100)),
                ('gcs_path', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('gs_uri', models.CharField(max_length=200)),
                ('date_of_measure', models.DateField()),
                ('days_old', models.IntegerField()),
                ('video_qc', models.CharField(choices=[('Poor', 'Poor'), ('OK', 'OK'), ('Good', 'Good')], max_length=20)),
                ('biomechanics_video_probability', models.DecimalField(decimal_places=2, max_digits=9)),
                ('biomechanics_video_score', models.CharField(max_length=10)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velox_app.horse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
