# Generated by Django 3.2.9 on 2021-12-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0004_measure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measure',
            old_name='gs_uri',
            new_name='gcs_gs_uri',
        ),
        migrations.RenameField(
            model_name='measure',
            old_name='url',
            new_name='gcs_url',
        ),
    ]
