# Generated by Django 3.2.9 on 2021-12-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0005_auto_20211208_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='gcs_gs_uri',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='gcs_url',
        ),
    ]
