# Generated by Django 3.2.9 on 2021-12-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0006_auto_20211208_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='gcs_filename',
            field=models.CharField(default='', max_length=100, verbose_name='GCS Filename'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measure',
            name='gcs_bucket',
            field=models.CharField(max_length=100, verbose_name='GCS Bucket'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='gcs_path',
            field=models.CharField(max_length=100, verbose_name='GCS Path'),
        ),
    ]
