# Generated by Django 3.2.9 on 2021-12-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0007_auto_20211208_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='active',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AlterField(
            model_name='horse',
            name='elite',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
    ]
