# Generated by Django 3.2.9 on 2021-12-14 11:40

from django.db import migrations, models


def update_instances(apps, schema_editor):
    """save instances so gcs_gs_uri field is populated for existing instances"""
    MyModel = apps.get_model('velox_app', 'Measure')
    for row in MyModel.objects.all():
        row.gcs_gs_uri = f'gs://{row.gcs_bucket}/{row.gcs_path}'
        # row.gcs_gs_uri = row.get_gcs_gs_uri()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0009_auto_20211210_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='gcs_gs_uri',
            field=models.CharField(blank=True, max_length=310, null=True, verbose_name='GCS GS URI'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='gcs_filename',
            field=models.CharField(max_length=200, verbose_name='GCS Filename'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='gcs_path',
            field=models.CharField(max_length=300, verbose_name='GCS Path'),
        ),
        migrations.AddIndex(
            model_name='measure',
            index=models.Index(fields=['gcs_gs_uri'], name='velox_app_m_gcs_gs__f0ec87_idx'),
        ),
        migrations.RunPython(update_instances, reverse_code=migrations.RunPython.noop)
    ]
