# Generated by Django 3.2.9 on 2021-12-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0010_auto_20211214_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='biomechanics_video_probability',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True),
        ),
    ]
