# Generated by Django 3.2.9 on 2021-12-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0011_alter_measure_biomechanics_video_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='biomechanics_video_probability',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
    ]
