# Generated by Django 3.2.9 on 2021-12-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0012_alter_measure_biomechanics_video_probability'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_type', models.CharField(choices=[('Video', 'Video'), ('Image', 'Image'), ('Tabular', 'Tabular')], max_length=30)),
                ('dataset_name', models.CharField(max_length=255)),
                ('dataset_id', models.CharField(max_length=255)),
                ('dataset_number_horses', models.IntegerField()),
                ('dataset_number_positive', models.IntegerField()),
                ('dataset_number_negative', models.IntegerField()),
                ('dataset_creation_date', models.DateTimeField()),
                ('model_type', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=255)),
                ('model_id', models.CharField(max_length=255)),
                ('model_creation_date', models.DateTimeField()),
                ('number_training', models.IntegerField()),
                ('number_test', models.IntegerField()),
                ('data_split', models.CharField(max_length=50)),
                ('average_precision', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('auc_pr', models.FloatField(blank=True, null=True)),
                ('auc_roc', models.FloatField(blank=True, null=True)),
                ('log_loss', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('algorithm', models.CharField(blank=True, max_length=255, null=True)),
                ('optimized_for', models.CharField(blank=True, max_length=255, null=True)),
                ('objective', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
