# Generated by Django 3.2.9 on 2022-01-05 10:30

from django.db import migrations
import velox_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0014_alter_mlmodel_dataset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='dlc_video',
            field=velox_app.models.GCSField(blank=True, null=True, verbose_name='DLC Video'),
        ),
    ]
