# Generated by Django 3.2.9 on 2022-01-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0017_alter_measure_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='biomechanics_gaf_probability',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='biomechanics_gaf_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='biomechanics_keypoint_probability',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='biomechanics_keypoint_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
