# Generated by Django 3.2.9 on 2022-01-12 14:10

from django.db import migrations, models
import velox_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0018_auto_20220110_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='cardio_quality',
            field=models.CharField(blank=True, choices=[('Poor', 'Poor'), ('OK', 'OK'), ('Good', 'Good')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='cardio_quality_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='cardio_type',
            field=models.CharField(blank=True, choices=[('Bullseye', 'Bullseye'), ('Turf/Off-speed Dirt', 'Turf/Off-speed Dirt'), ('Irregular/Immature', 'Irregular/Immature'), ('Small/Sprint', 'Small/Sprint')], default='Bullseye', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='cardio_type_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='cardio_video',
            field=velox_app.models.GCSField(blank=True, null=True, verbose_name='Cardio Video'),
        ),
        migrations.AddField(
            model_name='measure',
            name='cardio_video_probability',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='cardio_video_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
