# Generated by Django 3.2.9 on 2022-02-07 17:29

from django.db import migrations


def change_user_type(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ct = ContentType.objects.filter(
        app_label='auth',
        model='user'
    ).first()
    if ct:
        ct.app_label = 'velox_app'
        ct.save()


class Migration(migrations.Migration):
    dependencies = [
        ('velox_app', '0020_auto_20220113_1034'),
    ]

    operations = [
        migrations.RunPython(change_user_type, elidable=True),
    ]
