# Generated by Django 3.2.9 on 2022-02-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0022_auto_20220207_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
