# Generated by Django 3.2.9 on 2022-02-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0023_rename_user_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
