# Generated by Django 3.2.9 on 2022-03-03 14:40

from django.db import migrations, models
import velox_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0024_auto_20220207_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horse',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='measure',
            name='cardio_cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='dlc_jrg_image',
            field=velox_app.models.GCSField(blank=True, null=True, verbose_name='DLC JRG Image'),
        ),
    ]
