# Generated by Django 3.2.9 on 2022-03-31 11:49
import logging
from django.db import migrations, models


def get_measure_age(measure):
    """copied from Measure model"""

    if measure.days_old:
        if 365 >= measure.days_old >= 0:
            return 'Weanling'
        elif 680 >= measure.days_old >= 366:
            return 'Yearling'
        elif 1095 >= measure.days_old >= 681:
            return '2YO'
        elif 1460 >= measure.days_old >= 1096:
            return '3YO'
        elif measure.days_old >= 1461:
            return 'Older'
    return ''


def update_measure_type(apps, schema_editor):
    """touch Measures so it sets new field measure_type"""
    logging.info('starting migration')
    Measure = apps.get_model('velox_app', 'Measure')
    measures = Measure.objects.all()
    for measure in measures:
        measure.measure_type = f'{measure.horse.type} {get_measure_age(measure)}'
        measure.save()
    logging.info('migration completed')


class Migration(migrations.Migration):
    dependencies = [
        ('velox_app', '0026_update_gcs_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='measure_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(update_measure_type, migrations.RunPython.noop)
    ]
