# Generated by Django 3.2.9 on 2022-04-08 11:05

from django.db import migrations, models
import django.db.models.deletion
import velox_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0027_measure_measure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='biomechanics_cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='dlc_jrg_probability',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='dlc_jrg_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ImageMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_measure', models.DateField()),
                ('image', velox_app.models.GCSField(blank=True, null=True, verbose_name='Image')),
                ('morph_data', models.JSONField(blank=True, null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_measures', to='velox_app.horse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
