# Generated by Django 3.2.9 on 2022-04-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0028_auto_20220408_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemeasurement',
            name='calculated_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagemeasurement',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_measurements', to='velox_app.horse'),
        ),
    ]
