# Generated by Django 3.2.9 on 2022-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0029_auto_20220409_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='avg_distance_raced',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='broodmare_sire',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='cpi_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='dam',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='hurdle',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='sire',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='starts_country',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
