# Generated by Django 3.2.9 on 2022-05-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0031_update_cardio_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='avg_distance_raced',
            field=models.IntegerField(blank=True, null=True, verbose_name='Average Distance Raced'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='broodmare_sire',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Broodmare Sire'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='cpi_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='CPI Rating'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='starts_country',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Starts Country'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='cardio_type',
            field=models.CharField(blank=True, choices=[('Failed', 'Failed'), ('Bullseye Late Maturing Turf', 'Bullseye Late Maturing Turf'), ('Bullseye On-Pace Dirt Miler', 'Bullseye On-Pace Dirt Miler'), ('Bullseye Dirt Classic/Miler', 'Bullseye Dirt Classic/Miler'), ('Turf/Off Speed Dirt Miler', 'Turf/Off Speed Dirt Miler'), ('Bullseye Dirt Sprinter', 'Bullseye Dirt Sprinter'), ('Late Maturing Turf Sprinter/Miler', 'Late Maturing Turf Sprinter/Miler'), ('Australian Bullseye Turf Sprinter', 'Australian Bullseye Turf Sprinter'), ('Bullseye Dirt Miler', 'Bullseye Dirt Miler'), ('Euro Bullseye Turf Sprinter', 'Euro Bullseye Turf Sprinter'), ('On-pace Turf Sprinter/Miler', 'On-pace Turf Sprinter/Miler')], max_length=50, null=True),
        ),
    ]
