# Generated by Django 3.2.9 on 2022-06-09 15:53
import csv
from django.db import migrations, models
import django.db.models.deletion

input_filename = 'velox_app/migrations/files/0036_country_codes_import.csv'


def load_country_weights(apps, schema_editor):
    CountryWeight = apps.get_model('velox_app', 'CountryWeight')
    with open(input_filename) as f:
        csv_reader = csv.DictReader(f)
        for line in csv_reader:
            starts_country = line['starts_country'].strip()
            country = line['country'].strip()
            country_fullname = line['country_fullname'].strip()
            CountryWeight.objects.create(starts_country=starts_country, country=country,
                                         country_fullname=country_fullname)


def unset_unknow_starts_country(apps, schema_editor):
    Horse = apps.get_model('velox_app', 'Horse')
    horses = Horse.objects.all()
    country_codes = []
    with open(input_filename) as f:
        csv_reader = csv.DictReader(f)
        for line in csv_reader:
            starts_country = line['starts_country'].strip()
            country_codes.append(starts_country)
    for horse in horses:
        starts_country = horse.starts_country
        if (starts_country and not starts_country in country_codes) or starts_country == '':
            horse.starts_country = None
            horse.save()



class Migration(migrations.Migration):
    dependencies = [
        ('velox_app', '0033_auto_20220531_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryWeight',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_country',
                 models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='Starts Country')),
                ('country', models.CharField(blank=True,
                                             choices=[('North America', 'North America'), ('Europe', 'Europe'),
                                                      ('Overseas', 'Overseas'), ('Australia', 'Australia')],
                                             max_length=18, null=True)),
                ('country_weight', models.FloatField(blank=True, default=1.0, null=True)),
                ('country_fullname', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(load_country_weights, migrations.RunPython.noop),
        migrations.RunPython(unset_unknow_starts_country, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='horse',
            name='starts_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='horses', to='velox_app.countryweight'),
        ),
    ]
