# Generated by Django 3.2.9 on 2022-06-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0034_auto_20220609_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='pred_opt_dist',
            field=models.CharField(blank=True, choices=[('5-7f', '5-7f'), ('6-8f', '6-8f'), ('8-10f', '8-10f'), ('10f+', '10f+')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='prob_bio_model',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='prob_bio_model_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='prob_cardio_bio_model',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='prob_cardio_bio_model_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='prob_dna_cardio_bio_model',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='prob_dna_cardio_bio_model_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='countryweight',
            name='country',
            field=models.CharField(blank=True, choices=[('North America', 'North America'), ('South America', 'South America'), ('Europe', 'Europe'), ('Overseas', 'Overseas'), ('Australia', 'Australia'), ('Asia', 'Asia')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='country',
            field=models.CharField(blank=True, choices=[('North America', 'North America'), ('South America', 'South America'), ('Europe', 'Europe'), ('Overseas', 'Overseas'), ('Australia', 'Australia'), ('Asia', 'Asia')], max_length=15, null=True),
        ),
    ]
