# Generated by Django 3.2.9 on 2022-06-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0035_auto_20220614_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelMetadata',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('resource_name', models.CharField(max_length=500)),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('confusion_matrix', models.JSONField(blank=True, null=True)),
                ('annotations', models.JSONField(blank=True, null=True)),
                ('feature_attributions', models.JSONField(blank=True, null=True)),
                ('log_loss', models.FloatField(blank=True, null=True)),
                ('au_prc', models.FloatField(blank=True, null=True)),
                ('au_roc', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
