# Generated by Django 3.2.9 on 2022-10-25 19:16

from django.db import migrations, models
import velox_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0037_scorebins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlmodelmetadata',
            options={'ordering': ('-creation_time',)},
        ),
        migrations.AlterField(
            model_name='measure',
            name='cardio_video',
            field=velox_app.models.GCSField(blank=True, null=True, unique=True, verbose_name='Cardio Video'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='dlc_gaf_image',
            field=velox_app.models.GCSField(blank=True, null=True, unique=True, verbose_name='DLC GAF Image'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='dlc_h5_file',
            field=velox_app.models.GCSField(blank=True, null=True, unique=True, verbose_name='DLC H5 File'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='dlc_jrg_image',
            field=velox_app.models.GCSField(blank=True, null=True, unique=True, verbose_name='DLC JRG Image'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='dlc_video',
            field=velox_app.models.GCSField(blank=True, null=True, unique=True, verbose_name='DLC Video'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='gcs_path',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='GCS Path'),
        ),
    ]
