# Generated by Django 3.2.9 on 2022-11-04 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0038_auto_20221025_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horse_name', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(choices=[('Biomechanics Video Upload', 'biomechanics_video_upload'), ('Cardio Video Upload', 'cardio_video_upload')], max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velox_app.horse')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velox_app.measure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
