# Generated by Django 3.2.9 on 2023-02-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0040_image_measure_field_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemeasurement',
            name='prob_conform_model',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='prob_conform_model_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='prob_image',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='action',
            field=models.CharField(choices=[('biomechanics_video_upload', 'Biomechanics Video Upload'), ('cardio_video_upload', 'Cardio Video Upload')], max_length=50),
        ),
    ]
