# Generated by Django 3.2.9 on 2023-03-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0041_auto_20230209_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemeasurement',
            name='back_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='body_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='cannon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='femur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='femur_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='fetlock',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='fetlock_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='forearm_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='forelimb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='front_pastern',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='hind_cannon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='hind_fetlock_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='hip_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='hock_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='humerus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='imbalance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='ischium_hock',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='neck',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='pelvis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='pelvis_femur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='pelvis_horizontal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='procrustes_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='proportion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='scope',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='shoulder',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='shoulder_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='shoulder_horizontal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='thrust',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='tibia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='triangle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
