# Generated by Django 3.2.9 on 2023-05-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velox_app', '0043_update_image_measurements_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemeasurement',
            name='body_hind_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='forelimb_hind_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='forelimb_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='hind_length_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='leg_back_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='leg_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemeasurement',
            name='neck_length_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
